[REQ-pdf-import]
text = '''
Users should be able to import a PDF for annotation with an "import" button.
This will close the previously opened PDF.
'''

[SPC-pdf-import]
text = '''
The pdf import button will open a dialog that allows the user to upload a file.
For now no loading progress indication will be added.
'''
